version: '3.1'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
#        volumes:
#            - ./src/main/java/com/sondage/sondage/db/data:/data/db
        ports:
            - 27017:27017
